// Code generated by goctl. DO NOT EDIT.
package types

type BaseInfoAddReq struct {
	UserId   int64  `json:"userId"`
	ActvName string `json:"actvName"`
}

type BaseInfoAddResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type BaseInfoGetOneReq struct {
	UserId int64 `json:"userId"`
	ActvId int64 `json:"actvId"`
}

type BaseInfoGetOneResp struct {
	State    string  `json:"state"`
	Commont  string  `json:"commont"`
	BaseInfo BaseAll `json:"baseInfo"`
}

type BaseInfoGetAllReq struct {
	UserId  int64 `json:"userId"`
	NowPage int64 `json:"nowPage"`
	Count   int64 `json:"count"`
}

type BaseInfoGetAllResp struct {
	State    string      `json:"state"`
	Commont  string      `json:"commont"`
	BaseInfo []BaseTable `json:"baseInfo"`
	PageObj  Page        `json:"pageObj"`
}

type BaseTable struct {
	ActvId     int64  `json:"actvId"`
	StateCode  int64  `json:"stateCode"`
	ActvName   string `json:"actvName"`
	InfoDegree int64  `json:"infoDegree"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
}

type BaseInfoDelReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
}

type BaseInfoDelResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type BaseInfoEditReq struct {
	UserId   int64   `json:"userId"`
	BaseInfo BaseAll `json:"baseInfo"`
}

type BaseInfoEditResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type BaseAll struct {
	ActvId          int64  `json:"actvId"`
	StateCode       int64  `json:"stateCode"`
	TagCode         int64  `json:"tagCode"`
	ExamCode        int64  `json:"examCode"`
	PeriodCode      int64  `json:"periodCode"`
	AwardCode       int64  `json:"awardCode"`
	ActvName        string `json:"actvName"`
	Intro           string `json:"intro"`
	Pstr            string `json:"pstr"`
	InFoDegree      int64  `json:"inFoDegree"`
	StartTime       string `json:"startTime"`
	EndTime         string `json:"endTime"`
	ApplyStartTime  string `json:"applyStartTime"`
	ApplyEndTime    string `json:"applyEndTime"`
	ExamStartTime   string `json:"examStartTime"`
	ExamEndTime     string `json:"examEndTime"`
	UserId          int64  `json:"userId"`
	CreateUserName  string `json:"createUserName"`
	CreateUserTel   string `json:"createUserTel"`
	CreateUserEmail string `json:"createUserEmail"`
	CreateUserAvt   string `json:"createUserAvt"`
	CreateUserGrade int64  `json:"createUserGrade"`
}

type PublishReq struct {
	ActvId    int64  `json:"actvId"`
	UserId    int64  `json:"userId"`
	StartTime string `json:"startTime"`
}

type PubulishResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type OutReq struct {
	ActvId  int64  `json:"actvId"`
	UserId  int64  `json:"userId"`
	EndTime string `json:"endTime"`
}

type OutResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type DownReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
}

type DownResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type HotTagListReq struct {
}

type HotTagListResp struct {
	State      string   `json:"state"`
	Commont    string   `json:"commont"`
	HotTagList []HotTag `json:"hotTagList"`
}

type HotTag struct {
	Label    string         `json:"label"`
	TagId    int64          `json:"tagId"`
	Children []GradeBaseAll `json:"children"`
}

type GetTagShowListReq struct {
	PeriodCode []int64 `json:"periodCode"`
	AwardCode  []int64 `json:"awardCode"`
	TagCode    []int64 `json:"tagCode"`
	ExamCode   []int64 `json:"examCode"`
	NowPage    int64   `json:"nowPage"`
	Count      int64   `json:"count"`
}

type GetTagShowListResp struct {
	State    string         `json:"state"`
	Commont  string         `json:"commont"`
	BaseInfo []GradeBaseAll `json:"baseInfo"`
	PageObj  Page           `json:"pageObj"`
}

type Page struct {
	LenPage int64 `json:"lenPage"`
	Count   int64 `json:"count"`
	NowPage int64 `json:"nowPage"`
}

type GetAllNoUserReq struct {
}

type GetAllNoUserResp struct {
	State    string         `json:"state"`
	Commont  string         `json:"commont"`
	BaseInfo []GradeBaseAll `json:"baseInfo"`
}

type GradeBaseAll struct {
	ActvId         int64  `json:"actvId"`
	Grade          int64  `json:"grade"`
	UserId         int64  `json:"userId"`
	CreateUserName string `json:"createUserName"`
	TagCode        int64  `json:"tagCode"`
	ExamCode       int64  `json:"examCode"`
	PeriodCode     int64  `json:"periodCode"`
	AwardCode      int64  `json:"awardCode"`
	ActvName       string `json:"actvName"`
	Intro          string `json:"intro,optional"`
	Pstr           string `json:"pstr,optional"`
	ApplyStartTime string `json:"applyStartTime"`
	ApplyEndTime   string `json:"applyEndTime"`
}

type GetRankAllReq struct {
}

type GetRankAllResp struct {
	State           string         `json:"state"`
	Commont         string         `json:"commont"`
	WeekLookUpRank  []RankBaseInfo `json:"weekLookUpRank"`
	WeekHotRank     []RankBaseInfo `json:"weekHotRank"`
	SchoolCompeRank []RankUserInfo `json:"schoolCompeRank"`
}

type RankBaseInfo struct {
	ActvId         int64  `json:"actvId"`
	ActvName       string `json:"actvName"`
	UserId         int64  `json:"userId"`
	CreateUserName string `json:"createUserName"`
	Pstr           string `json:"pstr,optional"`
}

type RankUserInfo struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"UserName"`
	Avt      string `json:"avt"`
}

type GetRankHomeReq struct {
}

type GetRankHomeResp struct {
	State           string         `json:"state"`
	Commont         string         `json:"commont"`
	WeekLookUpRank  []RankBaseInfo `json:"weekLookUpRank"`
	WeekHotRank     []RankBaseInfo `json:"weekHotRank"`
	SchoolCompeRank []RankUserInfo `json:"schoolCompeRank"`
}

type InfoTreeAddReq struct {
	ActvId   int64  `json:"actvId"`
	UserId   int64  `json:"userId"`
	InfoTree []Leaf `json:"infoTree"`
}

type InfoTreeAddResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type Leaf struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Child   []Leaf `json:"children,optional"`
	Id      int64  `json:"id,optional"`
}

type InfoTreeDelReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
	InfoId int64 `json:"infoId"`
}

type InfoTreeDelResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type InfoTreeEditReq struct {
	ActvId   int64  `json:"actvId"`
	UserId   int64  `json:"userId"`
	InfoTree []Leaf `json:"infoTree"`
}

type InfoTreeEditResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type InfoTreeGetReq struct {
	ActvId int64 `json:"actvId"`
}

type InfoTreeGetResp struct {
	State    string `json:"state"`
	Commont  string `json:"commont"`
	InfoTree []Leaf `json:"infoTree"`
}

type InfoTreeAddOneReq struct {
	ParentId int64  `json:"parentId"`
	UserId   int64  `json:"userId"`
	ActvId   int64  `json:"actvId"`
	Title    string `json:"title"`
}

type InfoTreeAddOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type InfoTreeDelOneReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
	Id     int64 `json:"id"`
}

type InfoTreeDelOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type InfoTreeEditOneReq struct {
	ActvId  int64  `json:"actvId"`
	UserId  int64  `json:"userId"`
	Content string `json:"content"`
	Title   string `json:"title"`
	Id      int64  `json:"id"`
}

type InfoTreeEditOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type InfoTreeGetOneReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
	Id     int64 `json:"id"`
}

type InfoTreeGetOneResp struct {
	State   string  `json:"state"`
	Commont string  `json:"commont"`
	OneNode NodeObj `json:"nodeObj"`
}

type NodeObj struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

type UnitTreeGetReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
}

type UnitTreeGetResp struct {
	State    string         `json:"state"`
	Commont  string         `json:"commont"`
	UnitTree []UnitLeafList `json:"unitTree"`
}

type UnitLeafList struct {
	Id    int64          `json:"id,optional"`
	Title string         `json:"title"`
	Model int64          `json:"model"`
	Child []UnitLeafList `json:"child,optional"`
}

type UnitTreeAddOneReq struct {
	ParentId int64  `json:"parentId"`
	UserId   int64  `json:"userId"`
	ActvId   int64  `json:"actvId"`
	Title    string `json:"title"`
}

type UnitTreeAddOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type UnitTreeDelOneReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
	UnitId int64 `json:"UnitId"`
}

type UnitTreeDelOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type UnitTreeEditOneReq struct {
	UnitId  int64    `json:"UnitId"`
	ActvId  int64    `json:"actvId"`
	UserId  int64    `json:"userId"`
	OneNode UnitBase `json:"oneNode"`
}

type UnitTreeEditOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type UnitBase struct {
	Title     string `json:"title"`
	Tips      string `json:"tips"`
	FileName  string `json:"fileName,optional"`
	Model     int64  `json:"model"`
	ExamCode  int64  `json:"examCode"`
	Face      int64  `json:"face"`
	Count     int64  `json:"count"`
	During    int64  `json:"during,optional"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
}

type UnitTreeGetOneReq struct {
	ActvId int64 `json:"actvId"`
	UserId int64 `json:"userId"`
	UnitId int64 `json:"unitId"`
}

type UnitTreeGetOneResp struct {
	State   string   `json:"state"`
	Commont string   `json:"commont"`
	OneNode UnitBase `json:"node"`
	MaxExam int64    `json:"maxExam"`
}

type ExamInfoGetReq struct {
	ActvId int64 `json:"actvId"`
	UnitId int64 `json:"unitId"`
	UserId int64 `json:"userId"`
}

type ExamInfoGetResp struct {
	State          string          `json:"state"`
	Commont        string          `json:"commont"`
	QuestTitleList []QuestTitleOne `json:"questOne"`
}

type QuestTitleOne struct {
	Title  string `json:"title"`
	ExamId int64  `json:"examId"`
}

type ExamInfoAddOneReq struct {
	UserId       int64    `json:"userId"`
	ActvId       int64    `json:"actvId"`
	UnitId       int64    `json:"unitId"`
	QuestOneList QuestOne `json:"questOneList"`
}

type ExamInfoAddOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type QuestOne struct {
	ExamId int64   `json:"examId,optional"`
	Title  string  `json:"title"`
	Quest  string  `json:"quest"`
	Answer string  `json:"answer"`
	Img    string  `json:"img"`
	Method int64   `json:"method"`
	During int64   `json:"during,optional"`
	Score  float64 `json:"score"`
}

type ExamInfoDelOneReq struct {
	ActvId int64 `json:"actvId"`
	UnitId int64 `json:"unitId"`
	UserId int64 `json:"userId"`
	ExamId int64 `json:"examId"`
}

type ExamInfoDelOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type ExamInfoEditOneReq struct {
	ActvId       int64    `json:"actvId"`
	UnitId       int64    `json:"unitId"`
	UserId       int64    `json:"userId"`
	ExamId       int64    `json:"examId"`
	QuestOneList QuestOne `json:"questOneList"`
}

type ExamInfoEditOneResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type ExamInfoGetOneReq struct {
	ActvId int64 `json:"actvId"`
	UnitId int64 `json:"unitId"`
	UserId int64 `json:"userId"`
	ExamId int64 `json:"examId"`
}

type ExamInfoGetOneResp struct {
	State        string   `json:"state"`
	Commont      string   `json:"commont"`
	QuestOneList QuestOne `json:"questOneList"`
}

type AddHotReq struct {
	Date   string `json:"date"`
	ActvId int64  `json:"actvId"`
	UserId int64  `json:"userId"`
}

type AddHotResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AddJoinReq struct {
	Date   string `json:"date"`
	ActvId int64  `json:"actvId"`
	UserId int64  `json:"userId"`
}

type AddJoinResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AddLookupActvReq struct {
	Date   string `json:"date"`
	ActvId int64  `json:"actvId"`
	UserId int64  `json:"userId"`
}

type AddLookupActvResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type JoinReq struct {
	ActvId       int64 `json:"actvId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type JoinResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type OutJoinReq struct {
	JoinId int64 `json:"joinId"`
}

type OutJoinResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type CheckJoinReq struct {
	ActvId       int64 `json:"actvId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type CheckJoinResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
	JoinId  int64  `json:"joinId"`
}

type GetAllListActvReq struct {
	ActvId  int64 `json:"actvId"`
	NowPage int64 `json:"nowPage"`
	Count   int64 `json:"count"`
}

type GetAllListActvResp struct {
	State        string     `json:"state"`
	Commont      string     `json:"commont"`
	JoinUserList []UserInfo `json:"joinUserList"`
	PageObj      Page       `json:"pageObj"`
}

type UserInfo struct {
	UserName string `json:"userName"`
	Avt      string `json:"avt"`
	Tel      string `json:"tel"`
	UserId   int64  `json:"userId"`
	Grade    int64  `json:"grade"`
	Email    string `json:"email"`
	JoinDate string `json:"joinDate"`
	JoinId   int64  `json:"joinId"`
}

type GetAllListJoinReq struct {
	UserId  int64 `json:"userId"`
	NowPage int64 `json:"nowPage"`
	Count   int64 `json:"count"`
}

type GetAllListJoinResp struct {
	State    string      `json:"state"`
	Commont  string      `json:"commont"`
	JoinList []JoinTable `json:"joinList"`
	PageObj  Page        `json:"pageObj"`
}

type JoinAll struct {
	ActvId         int64  `json:"actvId"`
	StateCode      int64  `json:"stateCode"`
	TagCode        int64  `json:"tagCode"`
	ExamCode       int64  `json:"examCode"`
	PeriodCode     int64  `json:"periodCode"`
	AwardCode      int64  `json:"awardCode"`
	ActvName       string `json:"actvName"`
	Intro          string `json:"intro,optional"`
	Pstr           string `json:"pstr,optional"`
	ActvPics       string `json:"actvPics,optional"`
	StartTime      string `json:"startTime"`
	EndTime        string `json:"endTime"`
	ApplyStartTime string `json:"applyStartTime"`
	ApplyEndTime   string `json:"applyEndTime"`
	ExamStartTime  string `json:"examStartTime"`
	ExamEndTime    string `json:"examEndTime"`
}

type JoinTable struct {
	ActvId         int64  `json:"actvId"`
	StateCode      int64  `json:"stateCode"`
	ActvName       string `json:"actvName"`
	ExamStartTime  string `json:"examStartTime"`
	ExamEndTime    string `json:"examEndTime"`
	UserCreateId   int64  `json:"userCreateId"`
	UserCreateName string `json:"userCreateName"`
	Rank           int64  `json:"rank"`
}

type StartExamReq struct {
	ActvId       int64 `json:"actvId"`
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type StartExamResp struct {
	State     string      `json:"state"`
	Commont   string      `json:"commont"`
	ExamId    int64       `json:"examId"`
	QuestList []TitleExam `json:"questList"`
}

type TitleExam struct {
	ExamId int64    `json:"examId,optional"`
	Title  string   `json:"title"`
	Quest  []string `json:"quest"`
	Img    string   `json:"img"`
	Method int64    `json:"method"`
	Score  float64  `json:"score"`
}

type EndExamReq struct {
	ExamId       int64        `json:"examId"`
	ActvId       int64        `json:"actvId"`
	UnitId       int64        `json:"unitId"`
	UserCreateId int64        `json:"userCreateId"`
	UserJoinId   int64        `json:"userJoinId"`
	AnswerList   []AnswerExam `json:"answerList"`
	RecordInfo   ExamRecord   `json:"recordInfo"`
	StartTime    string       `json:"startTime"`
	EndTime      string       `json:"endTime"`
}

type EndExamResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AnswerExam struct {
	ExamId int64  `json:"examId"`
	Answer string `json:"answer"`
	During int64  `json:"during,optional"` //做这个题花了多少时间
}

type ExamRecord struct {
	Intro        string `json:"intro"`
	Illegal      string `json:"illegal"`
	IllegalIntro string `json:"illegalIntro"`
}

type StartExam52Req struct {
	ActvId       int64 `json:"actvId"`
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type StartExam52Resp struct {
	State     string        `json:"state"`
	Commont   string        `json:"commont"`
	ExamId    int64         `json:"examId"`
	QuestList []TitleExam52 `json:"questList"`
}

type TitleExam52 struct {
	ExamId int64    `json:"examId,optional"`
	Title  string   `json:"title"`
	Quest  []string `json:"quest"`
	Answer string   `json:"answer"`
	Img    string   `json:"img"`
	Method int64    `json:"method"`
	During int64    `json:"during,optional"`
	Score  float64  `json:"score"`
}

type EndExam52Req struct {
	ExamId     int64      `json:"examId"`
	StartTime  string     `json:"startTime"`
	EndTime    string     `json:"endTime"`
	RecordInfo ExamRecord `json:"recordInfo"`
	Score      float64    `json:"score"`
}

type EndExam52Resp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type StartExam53Req struct {
	ActvId       int64 `json:"actvId"`
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type StartExam53Resp struct {
	State     string        `json:"state"`
	Commont   string        `json:"commont"`
	ExamId    int64         `json:"examId"`
	QuestList []TitleExam53 `json:"questList"`
}

type TitleExam53 struct {
	ExamId int64    `json:"examId,optional"`
	Title  string   `json:"title"`
	Quest  []string `json:"quest"`
	Img    string   `json:"img"`
	Method int64    `json:"method"`
	During int64    `json:"during,optional"`
	Score  float64  `json:"score"`
}

type EndExam53Req struct {
	ExamId     int64        `json:"examId"`
	AnswerList []AnswerExam `json:"answerList"`
	RecordInfo ExamRecord   `json:"recordInfo"`
	StartTime  string       `json:"startTime"`
	EndTime    string       `json:"endTime"`
}

type EndExam53Resp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type GetRankListReq struct {
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	Count        int64 `json:"count"`
	NowPage      int64 `json:"nowPage"`
}

type GetRankListResp struct {
	State   string     `json:"state"`
	Commont string     `json:"commont"`
	List    []RankInfo `json:"list"`
	PageObj Page       `json:"pageObj"`
}

type RankInfo struct {
	ExamId       int64   `json:"examId"`
	ActvId       int64   `json:"actvId"`
	Rank         int64   `json:"rank"`
	UserName     string  `json:"UserName"`
	Avt          string  `json:"avt"`
	Tel          string  `json:"tel"`
	UserCreateId int64   `json:"userCreateId"`
	UserJoinId   int64   `json:"userJoinId"`
	Score        float64 `json:"score"`
	Intro        string  `json:"intro"`
	During       string  `json:"during"`
}

type GetListReq struct {
	ActvId       int64 `json:"actvId"`
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	NowPage      int64 `json:"nowPage"`
	Count        int64 `json:"count"`
}

type GetListResp struct {
	State   string         `json:"state"`
	Commont string         `json:"commont"`
	List    []JoinUnitInfo `json:"list"`
	PageObj Page           `json:"pageObj"`
}

type JoinUnitInfo struct {
	ExamId       int64   `json:"examId"`
	UserJoinId   int64   `json:"userJoinId"`
	UserName     string  `json:"userName"`
	Tel          string  `json:"tel"`
	Score        float64 `json:"score"`
	Intro        string  `json:"intro"`
	Illegal      string  `json:"illegal"`
	IllegalIntro string  `json:"illegalIntro"`
	During       string  `json:"during"`
}

type SimOssReq struct {
	ActvId       int64  `json:"actvId"`
	UnitId       int64  `json:"unitId"`
	UserCreateId int64  `json:"userCreateId"`
	UserJoinId   int64  `json:"userJoinId"`
	ImageUriA    string `json:"imageUriA"`
	ImageUriB    string `json:"imageUriB"`
}

type SimOssResp struct {
	State   string  `json:"state"`
	Commont string  `json:"commont"`
	SimVal  float64 `json:"simVal"`
}

type CheckExamReq struct {
	ActvId       int64 `json:"actvId"`
	UnitId       int64 `json:"unitId"`
	UserCreateId int64 `json:"userCreateId"`
	UserJoinId   int64 `json:"userJoinId"`
}

type CheckExamResp struct {
	State        string   `json:"state"`
	Commont      string   `json:"commont"`
	JoinUnitInfo JoinUnit `json:"joinUnitInfo"`
}

type JoinUnit struct {
	ExamId    int64   `json:"examId"`
	Score     float64 `json:"score"`     // 分数
	StartTime string  `json:"startTime"` // 考试时间
	EndTime   string  `json:"endTime"`   // 交卷时间
	Rank      int64   `json:"rank"`
}

type DelExamReq struct {
	ExamId int64 `json:"examId"`
}

type DelExamResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type UserLoginReq struct {
	UserName string `json:"userName"`
	Pwd      string `json:"pwd"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	State        string `json:"state"`
	Commont      string `json:"commont"`
	UserId       int64  `json:"userId"`
	Grade        int64  `json:"grade"`
}

type UserSignReq struct {
	UserName string `json:"userName"`
	Tel      string `json:"tel"`
	Pwd      string `json:"pwd"`
}

type UserSignResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	State        string `json:"state"`
	Commont      string `json:"commont"`
	UserId       int64  `json:"userId"`
}

type UserForgetPwdReq struct {
	Tel string `json:"tel"`
	Pwd string `json:"pwd"`
}

type UserForgetPwdResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AvtOssReq struct {
}

type AvtOssResp struct {
	State           string `json:"state"`
	Commont         string `json:"commont"`
	Region          string `json:"region"`          //地域（在创建 Bucket 的时候指定的中心位置），这里可能不知道具体地域怎么填其实就是 oss-cn-中心位置 ，例：region:'oss-cn-chengdu'，chengdu则是创建bucket是指定的位置成都。
	AccessKeyId     string `json:"accessKeyId"`     //阿里云产品的通用id
	AccessKeySecret string `json:"accessKeySecret"` //密钥
	Bucket          string `json:"bucket"`          //OSS 存储区域名
	DirPath         string `json:"dirPath"`
}

type EditInfoReq struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"userName"`
	Avt      string `json:"avt"`
	Tel      string `json:"tel"`
	Intro    string `json:"intro"`
	Email    string `json:"email"`
}

type EditInfoResp struct {
	State    string `json:"state"`
	Commont  string `json:"commont"`
	UserInfo Info   `json:"userInfo"`
}

type EditPwdReq struct {
	UserId int64  `json:"userId"`
	NewPwd string `json:"newPwd"`
	OldPwd string `json:"oldPwd"`
}

type EditPwdResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type GetInfoReq struct {
	UserId int64 `json:"userId"`
}

type GetInfoResp struct {
	State    string `json:"state"`
	Commont  string `json:"commont"`
	UserInfo Info   `json:"userInfo"`
}

type Info struct {
	UserName   string `json:"userName"`
	Avt        string `json:"avt"`
	Tel        string `json:"tel"`
	CreateTime string `json:"createTime"`
	UserId     int64  `json:"userId"`
	Grade      int64  `json:"grade"`
	JoinNum    int64  `json:"joinNum"`
	CreateNum  int64  `json:"createNum"`
	Intro      string `json:"intro"`
	Email      string `json:"email"`
}

type AddOneTagReq struct {
	ParentId int64  `json:"parentId"`
	Label    string `json:"label"`
}

type AddOneTagResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type DelOneTagReq struct {
	TagId int64 `json:"tagId"`
}

type DelOneTagResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type EditOneTagReq struct {
	TagId int64  `json:"tagId"`
	Label string `json:"label"`
}

type EditOneTagResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type GetTagListReq struct {
}

type GetTagListResp struct {
	State       string  `json:"state"`
	Commont     string  `json:"commont"`
	TagInfoList []Child `json:"TagInfo"`
}

type Child struct {
	Label    string  `json:"label"`
	TagId    int64   `json:"tagId"`
	Children []Child `json:"children"`
}

type KeepHotTagListReq struct {
	TagList []int64 `json:"tagList"`
}

type KeepHotTagListResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type HotTagId struct {
	TagId int64 `json:"tagId"`
}

type GetHotTagListReq struct {
}

type GetHotTagListResp struct {
	State   string  `json:"state"`
	Commont string  `json:"commont"`
	TagList []int64 `json:"tagList"`
}

type ApplyGradeReq struct {
	UserId     int64  `json:"userId"`
	ApplyIntro string `json:"applyIntro"`
	StartTime  string `json:"startTime"`
}

type ApplyGradeResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type GetNewGradeReq struct {
}

type GetNewGradeResp struct {
	State         string      `json:"state"`
	Commont       string      `json:"commont"`
	GradeInfoList []GradeInfo `json:"gradeInfo"`
}

type GradeInfo struct {
	GradeId    int64  `json:"gradeId"`
	UserId     int64  `json:"userId"`
	UserName   string `json:"userName"`
	UserTel    string `json:"userTel"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	ApplyIntro string `json:"applyIntro"`
	ReplyIntro string `json:"replyIntro"`
	GradeCode  int64  `json:"gradeCode"`
}

type GetPassGradeReq struct {
}

type GetPassGradeResp struct {
	State         string      `json:"state"`
	Commont       string      `json:"commont"`
	GradeInfoList []GradeInfo `json:"gradeInfo"`
}

type ReplyGradeReq struct {
	ReplyIntro string `json:"replyIntro"`
	EndTime    string `json:"endTime"`
	GradeId    int64  `json:"gradeId"`
	GradeCode  int64  `json:"gradeCode"`
	Garde      int64  `json:"garde"`
}

type ReplyGradeResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type GetOneGradeReq struct {
	UserId int64 `json:"userId"`
}

type GetOneGradeResp struct {
	State         string      `json:"state"`
	Commont       string      `json:"commont"`
	GradeInfoList []GradeInfo `json:"gradeInfo"`
}

type UserGradeInfo struct {
	GradeId    int64  `json:"gradeId"`
	UserId     int64  `json:"userId"`
	UserName   string `json:"userName"`
	UserTel    string `json:"userTel"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	ApplyIntro string `json:"applyIntro"`
	ReplyIntro string `json:"replyIntro"`
	GradeCode  int64  `json:"gradeCode"`
}

type GetAllGradeReq struct {
	Num int64 `json:"num"`
}

type GetAllGradeResp struct {
	State    string          `json:"state"`
	Commont  string          `json:"commont"`
	UserList []UserInfoGrade `json:"userList"`
}

type UserInfoGrade struct {
	UserName string `json:"userName"`
	Avt      string `json:"avt"`
	Intro    string `json:"intro"`
}

type AddApplyGradeReq struct {
	Date string `json:"date"`
}

type AddApplyGradeResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AddLoginReq struct {
	Date string `json:"date"`
}

type AddLoginResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}

type AddLookupWebReq struct {
	Date string `json:"date"`
}

type AddLookupWebResp struct {
	State   string `json:"state"`
	Commont string `json:"commont"`
}
